---
openapi: "3.0.3"

info:
  title: "habitra"
  version: "0.1.0"
  description: "Habit Tracker operated by API"

paths:
  "/v1/users":
    post:
      summary: "create user"
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: "takagi"
                password: "thisispassword"
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
              example:
                message: "Success."
        "400":
          description: "client error"
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
              examples:
                example1:
                  value:
                    message: "It is necessary to specify the username for registration."
                example2:
                  value:
                    message: "It is necessary to specify the password used for authentication."
        "409":
          description: "client error"
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
              example:
                message: "This user already exist."
  "/v1/users/{username}":
    put:
      summary: "update user"
      tags:
        - users
      security:
        - basicAuth: []
      parameters:
        - in: path
          name: username 
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - password
              properties:
                password:
                  type: string
              example:
                password: "thisisnewpassword"
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
              example:
                message: "Success."
        "400":
          description: "client error"
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
              example:
                message: "It is necessary to specify the password for update."
        "401":
          description: "client error"
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
              example:
                message: "Not authorized."
    delete:
      summary: "delete user"
      tags:
        - users
      security:
        - basicAuth: []
      parameters:
        - in: path
          name: username 
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
              example:
                message: "Success."
        "401":
          description: "client error"
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
              example:
                message: "Not authorized."

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
